apiVersion: v1
kind: Pod
metadata:
  name: pod-kogito-jmeter-benchmark
  namespace: fsi-kogito-benchmarking
  labels:
    app: kogito-jmeter-gatling-benchmark
spec:
  restartPolicy: Never
  volumes:
    - name: shared-file-storage
      emptyDir: {}
  containers:
    - name: jmeter-testing-status
      image: quay.io/lrangine/busybox:latest
      command: [ 'sh', '-c', 'echo Kogito Gatling Testing is completed. Exiting successfully' ]
  initContainers:
    - name: run-jmeter-test
      image: quay.io/lrangine/jmeter:latest
      command: ['/bin/bash', '-c', 'jmeter -n -t /opt/UsersDurationSimpleHT.jmx -Jschema=http -Jurl=process-quarkus-example-fsi-kogito-benchmarking.apps.mw-ocp4.cloud.lab.eng.bos.redhat.com -Jusers=60 -Jduration=120 -l /tmp/jmeter/res0.jtl && JMeterPluginsCMD.sh --generate-csv /tmp/jmeter/res0.csv --input-jtl /tmp/jmeter/res0.jtl --plugin-type AggregateReport && head -n 40 /tmp/jmeter/res0.jtl && cat /tmp/jmeter/res0.csv']
      volumeMounts:
        - name: shared-file-storage
          mountPath: /tmp/jmeter
    - name: upload-jmeter-reports-to-nooba
      image: quay.io/lrangine/aws-cli:latest
      args: ['s3','sync','/tmp/jmeter','s3://$(BUCKET_NAME)','--endpoint','https://$(BUCKET_HOST)', '--debug']
      envFrom:
        - configMapRef:
            name: obc-kogito-jmeter-claim
        - secretRef:
            name: obc-kogito-jmeter-claim
      env:
        - name: AWS_CA_BUNDLE
          value: /run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      volumeMounts:
        - name: shared-file-storage
          mountPath: /tmp/jmeter
